"""Writes Claudy/Views/Components/ClaudyWave.swift from frames/*.txt and wave.json.

The Swift file is generated: edit the frames or the sequence here, then rerun this script.

    python3 to_swift.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.abspath(os.path.join(ROOT, '..', '..', '..'))
OUT = os.path.join(REPO, 'Claudy', 'Views', 'Components', 'ClaudyWave.swift')

spec = json.load(open(os.path.join(ROOT, 'wave.json')))
ids = spec['frames']
grids = [open(os.path.join(ROOT, 'frames', f'{i}.txt')).read().splitlines() for i in ids]

lines = [
    '// Generated by docs/mascot/wave/source/to_swift.py from docs/mascot/wave. Do not edit by hand.',
    '',
    '/// Claudy waving hello, shown when a new version is out. Same isometric scene and inks as',
    "/// `ClaudyTyping`'s sprite, without the desk, plus `s` for the ground shadow.",
    '///',
    '/// The sequence starts and ends on the idle pose; the two idle steps are merged so the loop',
    '/// point never shows.',
    'enum ClaudyWave {',
    f"    static let columns = {spec['width']}",
    f"    static let rows = {spec['height']}",
    '',
    '    /// Frame index and duration in milliseconds, in playback order.',
    '    static let sequence: [(frame: Int, ms: Int)] = [',
]
steps = [(ids.index(s['frame']), s['ms']) for s in spec['sequence']]
if len(steps) > 1 and steps[0][0] == steps[-1][0]:
    steps[0] = (steps[0][0], steps[0][1] + steps[-1][1])
    steps.pop()
lines += [f'        ({f}, {ms}),  // {ids[f]}' for f, ms in steps]
lines += ['    ]', '', '    static let frames: [[String]] = [']
for frame_id, grid in zip(ids, grids):
    lines.append(f'        // {frame_id}')
    lines.append('        [')
    lines += [f'            "{row}",' for row in grid]
    lines.append('        ],')
lines += ['    ]', '}', '']
open(OUT, 'w').write('\n'.join(lines))
print('wrote', os.path.relpath(OUT, REPO), len(ids), 'frames', len(steps), 'steps')
